name: deploy

on:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "pubspec.lock"
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    name: deploy
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for Web
        run: flutter build web --base-href /sendpoints-web/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web
